- arguments: [ --cross, --refactor]

- extensions:
  - default: true


- ignore: { name: Avoid lambda }
- ignore: { name: Redundant lambda }
- ignore: { name: Unused LANGUAGE pragma }
- ignore: { name: Eta reduce }
- ignore: { name: Use camelCase }
# - ignore: { name: Use guards }
# - ignore: { name: Use fewer imports }
#- ignore: { name: Unused top binds }

# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
